ARG BASE_IMAGE=python:3.13
FROM ${BASE_IMAGE}
WORKDIR /app

COPY . /app/

# Install requirements
RUN pip install -r requirements.txt

EXPOSE 8000/tcp

RUN chmod +x /app/docker-entrypoint.sh
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["gunicorn", "kuhl_haus.magpie.api:run"]
# CMD ["python", "-m", "gunicorn", "-c", "gunicorn-config.py", "kuhl_haus.magpie.web.asgi:application"]
# CMD ["sh", "-c", "uvicorn kuhl_haus.magpie.wsgi --host 0.0.0.0 --port 8000"]
