# Generated by Django 6.0.3 on 2026-03-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpointmodel',
            name='environment',
            field=models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta'), ('gamma', 'gamma'), ('dev', 'dev'), ('local', 'local'), ('one-box', 'one-box'), ('ppe', 'ppe'), ('prod', 'prod'), ('production', 'production'), ('qa', 'qa'), ('staging', 'staging'), ('test', 'test'), ('uat', 'uat'), ('zeta', 'zeta')], default='prod', max_length=16),
        ),
    ]
